# Generated by Django 3.2.3 on 2021-05-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=100)),
                ('altitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('node_status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], max_length=10)),
                ('node_last_data_received', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEndnode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
