# Generated by Django 3.2.3 on 2021-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endnode', '0002_alter_endnode_node_last_data_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endnode',
            name='node_last_data_received',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
    ]
