# Generated by Django 3.2.3 on 2021-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('active', 'Aktif'), ('done', 'Tamamlandı')], max_length=10),
        ),
    ]
